# Generated by mirage.%%VERSION%%

-include Makefile.user
BUILD_DIR = mirage/
MIRAGE_DIR = mirage/mirage
UNIKERNEL_NAME = www-unix
OPAM = opam

all::
	@$(MAKE) --no-print-directory depends
	@$(MAKE) --no-print-directory build

.PHONY: all lock install-switch pull clean depend depends build mirage-repo-add mirage-repo-rm repo-add repo-rm depext-lockfile

repo-add:
	@echo -e "\e[2musing overlay repository mirage: [opam-overlays, mirage-overlays] \e[0m"
	$(OPAM) repo add opam-overlays https://github.com/dune-universe/opam-overlays.git || $(OPAM) repo set-url opam-overlays https://github.com/dune-universe/opam-overlays.git
	$(OPAM) repo add mirage-overlays https://github.com/dune-universe/mirage-opam-overlays.git || $(OPAM) repo set-url mirage-overlays https://github.com/dune-universe/mirage-opam-overlays.git


repo-rm:
	@echo -e "\e[2mremoving overlay repository [opam-overlays, mirage-overlays]\e[0m"
	$(OPAM) repo remove opam-overlays https://github.com/dune-universe/opam-overlays.git
	$(OPAM) repo remove mirage-overlays https://github.com/dune-universe/mirage-opam-overlays.git



depext-lockfile: $(MIRAGE_DIR)/$(UNIKERNEL_NAME)-monorepo.opam.locked
	echo " ↳ install external dependencies for monorepo"
	$(OPAM) monorepo depext -y -l $<


$(MIRAGE_DIR)/$(UNIKERNEL_NAME)-monorepo.opam.locked: $(MIRAGE_DIR)/$(UNIKERNEL_NAME)-monorepo.opam
	@$(MAKE) -s repo-add
	@echo " ↳ generate lockfile for monorepo dependencies"
	@$(OPAM) monorepo lock --build-only $(UNIKERNEL_NAME)-monorepo -l $@ --ocaml-version $(shell ocamlc --version); (ret=$$?; $(MAKE) -s repo-rm && exit $$ret)

lock::
	@$(MAKE) -B $(MIRAGE_DIR)/$(UNIKERNEL_NAME)-monorepo.opam.locked

pull:: $(MIRAGE_DIR)/$(UNIKERNEL_NAME)-monorepo.opam.locked
	@echo " ↳ fetch monorepo rependencies in the duniverse folder"
	@$(OPAM) monorepo pull -l $< -r $(BUILD_DIR)

install-switch:: $(MIRAGE_DIR)/$(UNIKERNEL_NAME)-switch.opam
	@echo " ↳ opam install switch dependencies"
	@$(OPAM) install $< --deps-only --yes
	@$(MAKE) -s depext-lockfile

depends depend::
	@$(MAKE) --no-print-directory lock
	@$(MAKE) --no-print-directory install-switch
	@$(MAKE) --no-print-directory pull

build::
	mirage build

clean::
	mirage clean
