		</div>
 
			<div class="clear_div"></div><!-- Clears above floated columns -->
		</div>
	
		<div id="footer">
			<h4>&copy; 2009-2010 Anil Madhavapeddy</h4>
			
			<ul>
@@BAR@@
			</ul>
		</div>

	</div>

<script type="text/javascript">
var disqus_shortname = 'openmirage';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/openmirage/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>

</html>
