<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>

	<title>openmirage :: @@TITLE@@</title>

	<link rel="stylesheet" type="text/css" href="/styles/index.css"/>
	
	<!--[if lt IE 7]>
	<script type="text/javascript" src="/scripts/ie7.js"></script>
	<![endif]-->
	
	<script type="text/javascript" src="/scripts/jquery.js"></script>
	<script type="text/javascript" src="/scripts/index.js"></script>
	<script type="text/javascript" src="/scripts/innerfade.js"></script>
	<script type="text/javascript" src="/scripts/easySlider1.7.js"></script>
</head>

<body>

	<div id="wrapper">
		<div id="header">
		  <div id="header_logo">
			<a id="logo" href="/"><img src="/graphics/mirage-logo.png" alt="Logo" /></a>
		  </div>
	  	  <div id="info_bar">
			<div id="linkbar">
				<ul>
                                   @@BAR@@
                                </ul>
			</div>
		  </div>
		</div>
	
		<div id="content">
