<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>

	<title>openmirage :: @@TITLE@@</title>

	<link rel="stylesheet" type="text/css" href="/styles/index.css"/>

        <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19610168-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

        </script>	
        @@EXTRA_HEAD@@
</head>

<body>

	<div id="wrapper">
		<div id="header">
		  <div id="header_logo">
			<a id="logo" href="/"><img src="/graphics/mirage-logo.png" alt="Logo" /></a>
		  </div>
	  	  <div id="info_bar">
			<div id="linkbar">
				<ul>
                                   @@BAR@@
                                </ul>
			</div>
		  </div>
		</div>
	
		<div id="content">
