<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>

	<title>@@TITLE@@</title>

	<link rel="stylesheet" type="text/css" href="/styles/index.css"/>
	
	<!--[if lt IE 7]>
	<script type="text/javascript" src="/scripts/ie7.js"></script>
	<![endif]-->
	
	<script type="text/javascript" src="/scripts/jquery.js"></script>
	<script type="text/javascript" src="/scripts/index.js"></script>
	<script type="text/javascript" src="/scripts/innerfade.js"></script>
	<script type="text/javascript" src="/scripts/easySlider1.7.js"></script>
</head>

<body>

	<div id="wrapper">
		<div id="header">
			<a id="logo" href="index.html"><img src="/graphics/mirage-logo.png" alt="Logo" /></a>
			
			<div id="search_bar">
				<form method="post" action="">
					<p><input id="search_field" name="search" type="text" /></p>
					<p><input id="search_button" type="submit" name="submit" value="Search" /></p>
				</form>
			</div>
		</div>
		
		<div id="info_bar">
			<div id="linkbar">
				<ul>
					<li><a class="current_page" href="/">Home</a></li>
					<li><a href="/download/">Download</a></li>
					<li><a href="/code/">Code</a></li>
					<li><a href="/resources/">Resources</a></li>
					<li><a href="/about/">About</a></li>
				</ul>
			</div>
		</div>
		
		<div id="content">
			@@CONTENT@@

			</div>
 
			<div class="clear_div"></div><!-- Clears above floated columns -->
		</div>
	
		<div id="footer">
			<h4>&copy; 2009 Anil Madhavapeddy</h4>
			
			<ul>
				<li><a href="/">Home</a></li>
				<li><a href="/download/">Download</a></li>
				<li><a href="/code/">Code</a></li>
				<li><a href="/resources/">Resources</a></li>
				<li><a href="/about/">About</a></li>
			</ul>
		</div>

	</div>
</body>

</html>
