(*NOTE this file was generated by is-mirage-broken -- DO NOT EDIT*)

open Cowabloga.Date
open Cowabloga.Wiki

let bactrian =
  {
    Cow.Atom.name = "Bactrian";
    uri           = None;
    email         = None;
  }
